image: php:8.2-fpm

pipelines:
  default:
    - parallel:
      - step:
          name: 'Build and Test'
          script:
            - bash ./devops/build_server.sh
            - bash ./devops/build_project.sh            
      - step:
          name: 'Lint'
          script:
            - echo "Your linting goes here..."
      - step:
          name: 'Security scan'
          script:
            - echo "Your security scan goes here..."
          
    # - step:
    #     name: 'Deployment to Staging'
    #     deployment: staging
    #     script:
    #       - echo "Your deployment to staging script goes here..."
    # - step:
    #     name: 'Deployment to Production'
    #     deployment: production
    #     trigger: 'manual'
    #     script:
    #       - echo "Your deployment to production script goes here..."

definitions:
  services:
    mysql:
      image: mysql:8.0
      environment:
        MYSQL_DATABASE: 'homestead'
        MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
        MYSQL_USER: 'homestead'
        MYSQL_PASSWORD: 'secret'


